In [3]:
import numpy as np

np.random.seed(1358)

n_sample = 10
x = np.linspace(1, 5, n_sample)
e = 0.1 * np.random.randn(n_sample)

y = 2 * x + 3 + e

Transpose of matrix:

In [4]:
import numpy as np

matrix = np.array([[3, 2, -1],
                   [-2, 7, 4],
                   [1, 6, 8]])

# Using numpy.transpose function
transpose_result1 = np.transpose(matrix)

# Using .T method
transpose_result2 = matrix.T

# Check if both methods give the same result
print("Transpose using numpy.transpose:", transpose_result1)
print("Transpose using .T method:", transpose_result2)

Transpose using numpy.transpose: [[ 3 -2  1]
 [ 2  7  6]
 [-1  4  8]]
Transpose using .T method: [[ 3 -2  1]
 [ 2  7  6]
 [-1  4  8]]


Element-wise product

In [5]:
matrix_A = np.array([[3, 2, -1],
                    [-2, 7, 4],
                    [1, 6, 8]])

matrix_B = np.array([[-1, 2, 3],
                    [5, -4, 9],
                    [-7, 8, 6]])

# Using numpy.multiply function
elementwise_product_result1 = np.multiply(matrix_A, matrix_B)

# Using * operator
elementwise_product_result2 = matrix_A * matrix_B

# Check if both methods give the same result
print("Element-wise product using numpy.multiply:", elementwise_product_result1)
print("Element-wise product using * operator:", elementwise_product_result2)


Element-wise product using numpy.multiply: [[ -3   4  -3]
 [-10 -28  36]
 [ -7  48  48]]
Element-wise product using * operator: [[ -3   4  -3]
 [-10 -28  36]
 [ -7  48  48]]


Matrix product

In [6]:
matrixA = np.array([[3, 2, -1],
                    [-2, 7, 4],
                    [1, 6, 8]])

matrixB = np.array([[-1, 2, 3],
                    [5, -4, 9],
                    [-7, 8, 6]])

# Using .dot method
matrix_product_result1 = matrixA.dot(matrixB)

# Using @ operator
matrix_product_result2 = matrixA @ matrixB

# Using numpy.matmul function
matrix_product_result3 = np.matmul(matrixA, matrixB)

# Check if all methods give the same result
print("Matrix product using .dot method:", matrix_product_result1)
print("Matrix product using @ operator:", matrix_product_result2)
print("Matrix product using numpy.matmul:", matrix_product_result3)

Matrix product using .dot method: [[ 14 -10  21]
 [  9   0  81]
 [-27  42 105]]
Matrix product using @ operator: [[ 14 -10  21]
 [  9   0  81]
 [-27  42 105]]
Matrix product using numpy.matmul: [[ 14 -10  21]
 [  9   0  81]
 [-27  42 105]]


Matrix Inversion

In [7]:
matrixA = np.array([[3, 2, -1],
                    [-2, 7, 4],
                    [1, 6, 8]])

# Using numpy.linalg.inv function
inverse_result = np.linalg.inv(matrixA)

# Check the result
print("Matrix inversion using numpy.linalg.inv:", inverse_result)

Matrix inversion using numpy.linalg.inv: [[ 0.20645161 -0.14193548  0.09677419]
 [ 0.12903226  0.16129032 -0.06451613]
 [-0.12258065 -0.10322581  0.16129032]]


Use Python and Numpy to verify the following properties (the following multiplications are considered matrix multiplications):

In [8]:
import numpy as np

# Given matrices
matrixA = np.array([[3, 2, -1],
                    [-2, 7, 4],
                    [1, 6, 8]])

matrixB = np.array([[-1, 2, 3],
                    [5, -4, 9],
                    [-7, 8, 6]])

matrixC = np.array([[-5, 4, 9],
                    [6, 1, 3],
                    [7, 2, -8]])

alpha = 2
beta = 3

# Property 1: (At)t = A
property_1_result = np.transpose(np.transpose(matrixA)) == matrixA
print("Property 1 (At)t = A:", property_1_result.all())

# Property 2: A + B = B + A
property_2_result = np.add(matrixA, matrixB) == np.add(matrixB, matrixA)
print("Property 2 A + B = B + A:", property_2_result.all())

# Property 3: A + (B + C) = (A + B) + C
property_3_result = np.add(matrixA, np.add(matrixB, matrixC)) == np.add(np.add(matrixA, matrixB), matrixC)
print("Property 3 A + (B + C) = (A + B) + C:", property_3_result.all())

# Property 4: (A + B)t = At + Bt
property_4_result = np.transpose(np.add(matrixA, matrixB)) == np.add(np.transpose(matrixA), np.transpose(matrixB))
print("Property 4 (A + B)t = At + Bt:", property_4_result.all())

# Property 5: AB != BA
property_5_result = not np.array_equal(np.dot(matrixA, matrixB), np.dot(matrixB, matrixA))
print("Property 5 AB != BA:", property_5_result)

# Property 6: A(BC) = (AB)C
property_6_result = np.array_equal(np.dot(matrixA, np.dot(matrixB, matrixC)), np.dot(np.dot(matrixA, matrixB), matrixC))
print("Property 6 A(BC) = (AB)C:", property_6_result)

# Property 7: A(B + C) = AB + AC
property_7_result = np.dot(matrixA, np.add(matrixB, matrixC)) == np.add(np.dot(matrixA, matrixB), np.dot(matrixA, matrixC))
print("Property 7 A(B + C) = AB + AC:", property_7_result.all())

# Property 8: (AB)t = BtAt
property_8_result = np.transpose(np.dot(matrixA, matrixB)) == np.dot(np.transpose(matrixB), np.transpose(matrixA))
print("Property 8 (AB)t = BtAt:", property_8_result.all())

# Property 9: (AB)(-1 in quadrant) = B(-1 in quadrant)A(-1 in quadrant)
property_9_result = np.dot(np.dot(matrixA, np.linalg.inv(matrixB)), np.linalg.inv(matrixA))
expected_result_9 = np.linalg.inv(np.dot(np.dot(matrixB, np.linalg.inv(matrixA)), np.linalg.inv(matrixB)))

# Check if the matrices are close within a tolerance
property_9_result_close = np.allclose(property_9_result, expected_result_9)
print("Property 9 (AB)(-1 in quadrant) = B(-1 in quadrant)A(-1 in quadrant):", property_9_result_close)

# Property 10: (At)(-1 in quadrant) = (A(-1 in quadrant))t
property_10_result = np.dot(np.transpose(matrixA), np.linalg.inv(matrixA))
expected_result_10 = np.transpose(np.linalg.inv(np.dot(np.transpose(matrixA), np.linalg.inv(matrixA))))

# Check if the matrices are close within a tolerance
property_10_result_close = np.allclose(property_10_result, expected_result_10)
print("Property 10 (At)(-1 in quadrant) = (A(-1 in quadrant))t:", property_10_result_close)


# Property 11: (α + β)A = αA + βA
property_11_result = np.dot((alpha + beta), matrixA) == np.add(np.dot(alpha, matrixA), np.dot(beta, matrixA))
print("Property 11 (α + β)A = αA + βA:", property_11_result.all())

# Property 12: α(A + B) = αA + αB
property_12_result = np.dot(alpha, np.add(matrixA, matrixB)) == np.add(np.dot(alpha, matrixA), np.dot(alpha, matrixB))
print("Property 12 α(A + B) = αA + αB:", property_12_result.all())

# Property 13: (αA)^(-1) = α^(-1) * A^(-1)
property_13_result = np.linalg.inv(alpha * matrixA)
expected_result_13 = (1/alpha) * np.linalg.inv(matrixA)

# Check if the matrices are close within a tolerance
property_13_result_close = np.allclose(property_13_result, expected_result_13)
print("Property 13 (αA)^(-1) = α^(-1) * A^(-1):", property_13_result_close)



Property 1 (At)t = A: True
Property 2 A + B = B + A: True
Property 3 A + (B + C) = (A + B) + C: True
Property 4 (A + B)t = At + Bt: True
Property 5 AB != BA: True
Property 6 A(BC) = (AB)C: True
Property 7 A(B + C) = AB + AC: True
Property 8 (AB)t = BtAt: True
Property 9 (AB)(-1 in quadrant) = B(-1 in quadrant)A(-1 in quadrant): False
Property 10 (At)(-1 in quadrant) = (A(-1 in quadrant))t: False
Property 11 (α + β)A = αA + βA: True
Property 12 α(A + B) = αA + αB: True
Property 13 (αA)^(-1) = α^(-1) * A^(-1): True
